server:
  servlet:
    context-path: /payment-api

message-queuing:
  queue: payment_queue
  exchange: payment_exchange
  routing-key: payment_routing_key

spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
